### ISSUE TITLE
No reaction 

### ISSUE THREAD

**Issue by vdvcoder** [rana01645/CodeGPT-Laravel#2]
WARN - okhttp3.OkHttpClient - A connection to https://api.openai.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

**Comment by rana01645** [comment]
Thanks, for sharing, it'll fixed on the next update!

**Comment by rana01645** [comment]
Fixed https://github.com/rana01645/CodeGPT-Laravel/commit/394ffafc3ac4d95af5184fd1b48357394b0f44f1

**Comment by CrazyFreeMan** [comment]
Build #PS-231.9161.47, built on June 22, 2023

No reaction for actions :(
