### ISSUE TITLE
please update to support latest version of phpstorm

### ISSUE THREAD

**Issue by it-can** [rana01645/CodeGPT-Laravel#6]
<img width="1295" alt="Scherm­afbeelding 2023-08-11 om 21 24 19" src="https://github.com/rana01645/CodeGPT-Laravel/assets/644288/2e6fbaaf-cd7a-4127-80bf-6a808298e04d">

**Comment by rana01645** [comment]
Thanks for reporting, updated!
https://plugins.jetbrains.com/plugin/21187-codegpt--chatgpt-for-laravel
